<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Source Embedding</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.python}</string>
			<key>comment</key>
			<string>Use Python grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.python</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.c}</string>
			<key>comment</key>
			<string>Use C grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.c</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.java}</string>
			<key>comment</key>
			<string>Use Java grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.java</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.xml}</string>
			<key>comment</key>
			<string>Use XML grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>text.xml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.shell}</string>
			<key>comment</key>
			<string>Use Shell grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.shell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.shell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.sql}</string>
			<key>comment</key>
			<string>Use SQL grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.sql</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sql</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.scheme}</string>
			<key>comment</key>
			<string>Use Scheme grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.scheme</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.scheme</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.ruby}</string>
			<key>comment</key>
			<string>Use Ruby grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.ruby</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.rails}</string>
			<key>comment</key>
			<string>Use Ruby on Rails grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.ruby.rails</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.rails</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.r}</string>
			<key>comment</key>
			<string>Use R grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.r</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.r</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.prolog}</string>
			<key>comment</key>
			<string>Use Prolog grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.prolog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.prolog</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.php}</string>
			<key>comment</key>
			<string>Use PHP grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>text.html.php</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.php</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.perl}</string>
			<key>comment</key>
			<string>Use Perl grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.perl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.perl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.ocaml}</string>
			<key>comment</key>
			<string>Use OCaml grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.ocaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ocaml</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.objc}</string>
			<key>comment</key>
			<string>Use Objective C grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.objc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.objc</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.markdown}</string>
			<key>comment</key>
			<string>Use Markdown grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>text.html.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.markdown</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.lua}</string>
			<key>comment</key>
			<string>Use Lua grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.lua</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.lua</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.lisp}</string>
			<key>comment</key>
			<string>Use Lisp grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.lisp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.lisp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.latex}</string>
			<key>comment</key>
			<string>Use LaTeX grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>text.tex.latex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex.latex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.java}</string>
			<key>comment</key>
			<string>Use Java grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.java</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.java</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.js}</string>
			<key>comment</key>
			<string>Use JavaScript grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.js</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.html}</string>
			<key>comment</key>
			<string>Use HTML grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>text.html.basic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.haskell}</string>
			<key>comment</key>
			<string>Use Haskell grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.haskell</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.haskell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.go}</string>
			<key>comment</key>
			<string>Use Go grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.go</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.go</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.fortran}</string>
			<key>comment</key>
			<string>Use Fortran grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.fortran.modern</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.fortran</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.erlang}</string>
			<key>comment</key>
			<string>Use Erlang grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.erlang</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.erlang</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.css}</string>
			<key>comment</key>
			<string>Use CSS grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.css</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.c#}</string>
			<key>comment</key>
			<string>Use C# grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.cs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.c\+\+}</string>
			<key>comment</key>
			<string>Use C++ grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.c++</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c++</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~\s*{.arduino}</string>
			<key>comment</key>
			<string>Use Arduino grammar</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source.c++.arduino</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.c++.arduino</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>~~~</string>
			<key>comment</key>
			<string>Unspecified generic source code</string>
			<key>end</key>
			<string>~~~</string>
			<key>name</key>
			<string>source</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>meta.embed</string>
	<key>uuid</key>
	<string>89F5C768-EC71-49DC-803E-AE1D4B4D8E39</string>
</dict>
</plist>
